language: scala

branches:
  only:
    - master

services:
  - docker

script:
  - sbt test
  - docker build -t renorvator-wol .

before_deploy:
  - docker tag renorvator-wol $DOCKER_IMAGE
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push $DOCKER_IMAGE
  skip_cleanup: true
  on:
    branch: master
